### ISSUE TITLE
i am getting the error whenn i trying to run it can you please slove it

### ISSUE THREAD

**Issue by joshvayu** [mohameosam/open_excel#1]
nexpected Exception: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/vayu/PycharmProjects/excel']
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 148, in run
    pbex = PlaybookExecutor(playbooks=self.args, inventory=inventory, variable_manager=variable_manager, loader=loader, options=self.options, passwords=passwords)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 63, in __init__
    self._tqm = TaskQueueManager(inventory=inventory, variable_manager=variable_manager, loader=loader, options=options, passwords=self.passwords)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 97, in __init__
    self._connection_lockfile = tempfile.TemporaryFile()
  File "/usr/lib/python2.7/tempfile.py", line 504, in TemporaryFile
    dir = gettempdir()
  File "/usr/lib/python2.7/tempfile.py", line 275, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
    ("No usable temporary directory found in %s" % dirlist))
IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/vayu/PycharmProjects/excel']

**Comment by mohameosam** [comment]
It is an IOError, you have to have a valid directory specified in the code for it to work. Please share your code if you are still running into issues.
